### ISSUE TITLE
Cross-site resource warning related to Cookies

### ISSUE THREAD

**Issue by olavoasantos** [unravelin/ravelinjs#31]
## Description

Ravelin is setting cookies without the `SameSite` attribute. With a change in privacy defaults of browsers, the behaviour will soon only support cookies with the same-site flag set to true or marked as secure. For Chrome, this is planned to roll out with Chrome 80 in early 2020, probably at the start of February.

## Warning

```
A cookie associated with a cross-site resource at https://ravelin.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

## Fix

When setting cookies, the ravelinjs lib should be setting the cookies with the proper configuration.

**Comment by icio** [comment]
Hi @olavoasantos! Thanks for reporting this to us. I was aware of the impending [Same-Site: Lax default](https://www.chromestatus.com/feature/5088147346030592) (a default with which ravelinjs should continue to work as expected), but somehow the [Same-Site: None requiring Secure](https://www.chromestatus.com/feature/5633521622188032) had completely passed me by. We'll figure this out and keep you posted.

**Comment by icio** [comment]
Hello again @olavoasantos. Wanting to let you know what I've just pushed out a change to the cookie-setting part of this library (in a private repo) which will add `SameSite=None;Secure` to pages served over HTTPS and `SameSite=Lax` to pages served over HTTP. With this deploy, the warnings should now be gone from your homepage :smile: 

If you have any further questions or concerns, please don't hesitate to reach out here or in our shared slack. Hope that helps :+1:

**Comment by olavoasantos** [comment]
@icio Thank you for the update! I'll let you know if anything comes up.
